[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2e7bcf"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f4f8"
textColor = "#2d3748"
